/**
 * Auto Apply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VacancyDto } from './vacancy-dto';


export interface VacanciesResponseDto { 
    vacancies: Array<VacancyDto>;
    total: number;
    page: number;
    perPage: number;
    pages?: number | null;
}

