/**
 * Auto Apply API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalaryDto } from './salary-dto';
import { EmployerDto } from './employer-dto';


export interface VacancyDto { 
    id: string;
    name: string;
    url: string;
    area: string;
    salary?: SalaryDto | null;
    employer: EmployerDto;
    experience: string;
    employment: string;
    schedule: string;
    responseLetterRequired: boolean;
    requirement?: string | null;
    responsibility?: string | null;
    publishedAt: string;
}

